[package]
name = "shared-utils"
version.workspace = true
edition.workspace = true

[dependencies]
toml = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"]}
mdns-sd = { workspace = true }
pnet = { workspace = true }
