[package]
name = "server-utils"
version.workspace = true
edition.workspace = true

[dependencies]
rand = { workspace = true }
anyhow = { workspace = true }
xxhash-rust = { workspace = true }
shared-utils = { workspace = true }
gethostname = { workspace = true }
